/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccessibleStatusBar.java
 *
 * Created on Dec 1, 2009, 9:57:26 AM
 */

package edu.byu.swing.components;

import edu.byu.framework.swing.util.BYUAppender;
import edu.byu.framework.swing.util.BYUAppenderListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import org.apache.log4j.Level;
import org.apache.log4j.spi.LoggingEvent;

/**
 *
 * @author wct5
 */
public class AccessibleStatusBar extends javax.swing.JPanel {
	private static final long serialVersionUID = -1073716944486794166L;

    private int count = 0;
    private final static int STATUS_TIMEOUT = 4000;
    private final Timer timer;

    /** Creates new form AccessibleStatusBar */
    public AccessibleStatusBar() {
        initComponents();
		timer = new Timer(STATUS_TIMEOUT, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                if (count > 0) {
                    return;
                }
                lblLogMessage.setText("");
            }
        });
        BYUAppender.addListener(new BYUAppenderListener() {

            public void log(LoggingEvent loggingEvent) {
                switch (loggingEvent.getLevel().toInt()) {
                    case Level.INFO_INT:
                        lblLogMessage.setText(loggingEvent.getMessage().toString());
                        if (count > 0) {
                            timer.restart();
                        }
                        break;
                    case Level.ERROR_INT:
                        lblLogMessage.setText("<html><font color=red>Error: </font>" + loggingEvent.getMessage().toString());
                        timer.restart();
                        break;
                }
            }
        });
        timer.start();
    }

	public void setSystemText(String text) {
		synchronized (lblSystemText) {
			lblSystemText.setText(text);
		}
	}

	public javax.swing.JProgressBar getProgressBar() {
		return pbProgressBar;
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pbProgressBar = new javax.swing.JProgressBar();
        lblSystemText = new javax.swing.JLabel();
        lblLogMessage = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(1280, 20));
        setMinimumSize(new java.awt.Dimension(800, 20));
        setPreferredSize(new java.awt.Dimension(1024, 20));
        setLayout(new java.awt.GridBagLayout());

        pbProgressBar.setMaximumSize(new java.awt.Dimension(150, 16));
        pbProgressBar.setMinimumSize(new java.awt.Dimension(150, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(pbProgressBar, gridBagConstraints);

        lblSystemText.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(lblSystemText, gridBagConstraints);

        lblLogMessage.setText("         ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(lblLogMessage, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogMessage;
    private javax.swing.JLabel lblSystemText;
    private javax.swing.JProgressBar pbProgressBar;
    // End of variables declaration//GEN-END:variables

}
