/*
 * ByuStatusBar.java
 *
 * Created on Jan 27, 2009, 1:25:06 PM
 */
package edu.byu.swing.components;

import edu.byu.framework.swing.util.BYUAppender;
import edu.byu.framework.swing.util.BYUAppenderListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import org.apache.log4j.Level;
import org.apache.log4j.spi.LoggingEvent;

/**
 * Basic status bar, displaying log messages and a progress bar.
 * @author tylers2
 * @version 1.0.0
 * @since 1.0.0
 */
public class ByuStatusBar extends javax.swing.JPanel {

    private static final long serialVersionUID = -1073716944486793055L;
    private int count = 0;
    private final static int STATUS_TIMEOUT = 4000;
    private final Timer timer;

    /** Creates new form ByuStatusBar */
    public ByuStatusBar() {
        initComponents();
        timer = new Timer(STATUS_TIMEOUT, new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                if (count > 0) {
                    return;
                }
                lblText.setText("");
            }
        });
        BYUAppender.addListener(new BYUAppenderListener() {

            public void log(LoggingEvent loggingEvent) {
                switch (loggingEvent.getLevel().toInt()) {
                    case Level.INFO_INT:
                        lblText.setText(loggingEvent.getMessage().toString());
                        if (count > 0) {
                            timer.restart();
                        }
                        break;
                    case Level.ERROR_INT:
                        lblText.setText("<html><font color=red>Error: </font>" + loggingEvent.getMessage().toString());
                        timer.restart();
                        break;
                }
            }
        });
        timer.start();
    }

    /**
     * Starts progress bar
     */
    public synchronized void startBusy() {
        count++;
        pbStatus.setIndeterminate(true);
        timer.stop();
    }

    /**
     * Stops progress bar
     */
    public synchronized void stopBusy() {
        count--;
        if (count <= 0) {
            pbStatus.setIndeterminate(false);
            count = 0;
            timer.restart();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbStatus = new javax.swing.JProgressBar();
        lblText = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblText, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblText;
    private javax.swing.JProgressBar pbStatus;
    // End of variables declaration//GEN-END:variables
}
