/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PagerDialog.java
 *
 * Created on Aug 11, 2009, 11:21:32 AM
 */

package edu.byu.swing.components;

import edu.byu.framework.swing.util.DialogUtil;
import edu.byu.swing.icons.Actions;
import edu.byu.swing.icons.IconHelper;
import edu.byu.swing.icons.IconSizes;
import java.awt.BorderLayout;
import java.awt.Frame;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author tylers2
 */
public class PagerDialog<T> extends javax.swing.JDialog {
    private static final long serialVersionUID = 1L;
    private final static Icon OKAY_ICON = IconHelper.getIcon(Actions.LIST_ADD, IconSizes.SMALL);
    private final static Icon CANCEL_ICON = IconHelper.getIcon(Actions.PROCESS_STOP, IconSizes.SMALL);
    private final Pager<T> pager;
    private T item;

    /** Creates new form PagerDialog
     * @param parent
     * @param pager
     */
    public PagerDialog(final Frame parent, final Pager<T> pager) {
        super(parent, true);
        this.pager = pager;
        initComponents();
        main.add(pager);
        pager.getModel().getComponent().addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() < 2 || pager.getSelectedItem() == null) {
                    return;
                }
                doSelect();
            }
        });
        DialogUtil.centerDialog(parent, this);
    }

    public T getSelectedItem() {
        return item;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        javax.swing.JPanel buttonPanel = new javax.swing.JPanel();
        btnSelect = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 340));

        main.setLayout(new javax.swing.BoxLayout(main, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        btnSelect.setIcon(OKAY_ICON);
        btnSelect.setText("Select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnCancel.setIcon(CANCEL_ICON);
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap(506, Short.MAX_VALUE)
                .addComponent(btnSelect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addGap(2, 2, 2))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnSelect)
                .addComponent(btnCancel))
        );

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        doSelect();
}//GEN-LAST:event_btnSelectActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void doSelect() {
        setVisible(false);
        item = pager.getSelectedItem();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSelect;
    private javax.swing.JPanel main;
    // End of variables declaration//GEN-END:variables

}
