//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.16 at 12:58:24 PM MST 
//


package edu.byu.edge.client.controldates.domain;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for date_rowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="date_rowType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="date_type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="year_term" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="start_date" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="end_date" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "date_rowType", propOrder = {
    "dateType",
    "yearTerm",
    "startDate",
    "endDate",
    "description"
})
public class DateRowType implements Serializable{

	private static final long serialVersionUID = -1301451422719310865L;

	@XmlElement(name = "date_type", required = true)
    protected String dateType;
    @XmlElement(name = "year_term", required = true)
    protected String yearTerm;
    @XmlElement(name = "start_date", required = true)
    protected String startDate;
    @XmlElement(name = "end_date", required = true)
    protected String endDate;
    @XmlElement(required = true)
    protected String description;

    /**
     * Gets the value of the dateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateType() {
        return dateType;
    }

    /**
     * Sets the value of the dateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateType(String value) {
        this.dateType = value;
    }

    /**
     * Gets the value of the yearTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYearTerm() {
        return yearTerm;
    }

    /**
     * Sets the value of the yearTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYearTerm(String value) {
        this.yearTerm = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndDate(String value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }
    
    /* (non-Javadoc)
   	 * @see java.lang.Object#hashCode()
   	 */
   	@Override
   	public int hashCode() {
   		final int prime = 31;
   		int result = 1;
   		result = prime * result + ((dateType == null) ? 0 : dateType.hashCode());
   		result = prime * result + ((description == null) ? 0 : description.hashCode());
   		result = prime * result + ((endDate == null) ? 0 : endDate.hashCode());
   		result = prime * result + ((startDate == null) ? 0 : startDate.hashCode());
   		result = prime * result + ((yearTerm == null) ? 0 : yearTerm.hashCode());
   		return result;
   	}

   	/* (non-Javadoc)
   	 * @see java.lang.Object#equals(java.lang.Object)
   	 */
   	@Override
   	public boolean equals(Object obj) {
   		if (this == obj) {
   			return true;
   		}
   		if (obj == null) {
   			return false;
   		}
   		if (!(obj instanceof DateRowType)) {
   			return false;
   		}
   		DateRowType other = (DateRowType) obj;
   		if (dateType == null) {
   			if (other.dateType != null) {
   				return false;
   			}
   		} else if (!dateType.equals(other.dateType)) {
   			return false;
   		}
   		if (description == null) {
   			if (other.description != null) {
   				return false;
   			}
   		} else if (!description.equals(other.description)) {
   			return false;
   		}
   		if (endDate == null) {
   			if (other.endDate != null) {
   				return false;
   			}
   		} else if (!endDate.equals(other.endDate)) {
   			return false;
   		}
   		if (startDate == null) {
   			if (other.startDate != null) {
   				return false;
   			}
   		} else if (!startDate.equals(other.startDate)) {
   			return false;
   		}
   		if (yearTerm == null) {
   			if (other.yearTerm != null) {
   				return false;
   			}
   		} else if (!yearTerm.equals(other.yearTerm)) {
   			return false;
   		}
   		return true;
   	}


}
