//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.05 at 03:42:36 PM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "uri://byu/c/rest/v1/academic/controls/controldatesws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.byu.edge.client.controldates.domain;
