//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.05 at 03:42:36 PM MDT 
//


package edu.byu.edge.client.controldates.domain;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for responseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="responseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="request_count" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="date_list" type="{uri://byu/c/rest/v1/academic/controls/controldatesws}date_listType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "responseType", propOrder = {
    "requestCount",
    "dateList"
})
public class ResponseType {

    @XmlElement(name = "request_count", required = true)
    protected BigInteger requestCount;
    @XmlElement(name = "date_list", required = true)
    protected DateListType dateList;

    /**
     * Gets the value of the requestCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRequestCount() {
        return requestCount;
    }

    /**
     * Sets the value of the requestCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRequestCount(BigInteger value) {
        this.requestCount = value;
    }

    /**
     * Gets the value of the dateList property.
     * 
     * @return
     *     possible object is
     *     {@link DateListType }
     *     
     */
    public DateListType getDateList() {
        return dateList;
    }

    /**
     * Sets the value of the dateList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateListType }
     *     
     */
    public void setDateList(DateListType value) {
        this.dateList = value;
    }

}
